# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72b9ab4a930fd0167c6375323fa6a52f06d113e81128de565241e3ff81b692ae7be57053b6fae9a49e756c99a3604551ecedfdd533bb8eac03d72ddcd8b5afee

test:
  secret_key_base: 20f02bb62af01937829b0775ade812d350b8c593f46b3dbfb6858471464b35f0151827ff81aa901e6e1e33b6ea3011288a4b99584d5e4d8e202ae99389fae697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
